/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeReviewRouteImport } from './routes/resume-review'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as MockInterviewRouteImport } from './routes/mock-interview'
import { Route as IndexRouteImport } from './routes/index'

const ResumeReviewRoute = ResumeReviewRouteImport.update({
  id: '/resume-review',
  path: '/resume-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const MockInterviewRoute = MockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mock-interview': typeof MockInterviewRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-review': typeof ResumeReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mock-interview': typeof MockInterviewRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-review': typeof ResumeReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mock-interview': typeof MockInterviewRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-review': typeof ResumeReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mock-interview' | '/resume-builder' | '/resume-review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mock-interview' | '/resume-builder' | '/resume-review'
  id:
    | '__root__'
    | '/'
    | '/mock-interview'
    | '/resume-builder'
    | '/resume-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MockInterviewRoute: typeof MockInterviewRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  ResumeReviewRoute: typeof ResumeReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-review': {
      id: '/resume-review'
      path: '/resume-review'
      fullPath: '/resume-review'
      preLoaderRoute: typeof ResumeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview': {
      id: '/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof MockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MockInterviewRoute: MockInterviewRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  ResumeReviewRoute: ResumeReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
