/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSkillAssessmentRouteImport } from './routes/_authenticated/skill-assessment'
import { Route as AuthenticatedResumeReviewRouteImport } from './routes/_authenticated/resume-review'
import { Route as AuthenticatedResumeBuilderRouteImport } from './routes/_authenticated/resume-builder'
import { Route as AuthenticatedMockInterviewRouteImport } from './routes/_authenticated/mock-interview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillAssessmentRoute =
  AuthenticatedSkillAssessmentRouteImport.update({
    id: '/_authenticated/skill-assessment',
    path: '/skill-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResumeReviewRoute =
  AuthenticatedResumeReviewRouteImport.update({
    id: '/_authenticated/resume-review',
    path: '/resume-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResumeBuilderRoute =
  AuthenticatedResumeBuilderRouteImport.update({
    id: '/_authenticated/resume-builder',
    path: '/resume-builder',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMockInterviewRoute =
  AuthenticatedMockInterviewRouteImport.update({
    id: '/_authenticated/mock-interview',
    path: '/mock-interview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/resume-review': typeof AuthenticatedResumeReviewRoute
  '/skill-assessment': typeof AuthenticatedSkillAssessmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/resume-review': typeof AuthenticatedResumeReviewRoute
  '/skill-assessment': typeof AuthenticatedSkillAssessmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/_authenticated/resume-builder': typeof AuthenticatedResumeBuilderRoute
  '/_authenticated/resume-review': typeof AuthenticatedResumeReviewRoute
  '/_authenticated/skill-assessment': typeof AuthenticatedSkillAssessmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mock-interview'
    | '/resume-builder'
    | '/resume-review'
    | '/skill-assessment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mock-interview'
    | '/resume-builder'
    | '/resume-review'
    | '/skill-assessment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/mock-interview'
    | '/_authenticated/resume-builder'
    | '/_authenticated/resume-review'
    | '/_authenticated/skill-assessment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedMockInterviewRoute: typeof AuthenticatedMockInterviewRoute
  AuthenticatedResumeBuilderRoute: typeof AuthenticatedResumeBuilderRoute
  AuthenticatedResumeReviewRoute: typeof AuthenticatedResumeReviewRoute
  AuthenticatedSkillAssessmentRoute: typeof AuthenticatedSkillAssessmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skill-assessment': {
      id: '/_authenticated/skill-assessment'
      path: '/skill-assessment'
      fullPath: '/skill-assessment'
      preLoaderRoute: typeof AuthenticatedSkillAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume-review': {
      id: '/_authenticated/resume-review'
      path: '/resume-review'
      fullPath: '/resume-review'
      preLoaderRoute: typeof AuthenticatedResumeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume-builder': {
      id: '/_authenticated/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof AuthenticatedResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mock-interview': {
      id: '/_authenticated/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof AuthenticatedMockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedMockInterviewRoute: AuthenticatedMockInterviewRoute,
  AuthenticatedResumeBuilderRoute: AuthenticatedResumeBuilderRoute,
  AuthenticatedResumeReviewRoute: AuthenticatedResumeReviewRoute,
  AuthenticatedSkillAssessmentRoute: AuthenticatedSkillAssessmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
